#pragma once

#define TINYGLTF_NO_EXTERNAL_IMAGE
#define TINYGLTF_NO_STB_IMAGE
#define TINYGLTF_NO_STB_IMAGE_WRITE
#define TINYGLTF_NO_INCLUDE_STB_IMAGE
#define TINYGLTF_NO_INCLUDE_STB_IMAGE_WRITE
#define TINYGLTF_USE_CPP14
#define TINYGLTF_IMPLEMENTATION

#include <tiny_gltf.h>

#undef TINYGLTF_NO_EXTERNAL_IMAGE
#undef TINYGLTF_NO_STB_IMAGE
#undef TINYGLTF_NO_STB_IMAGE_WRITE
#undef TINYGLTF_NO_INCLUDE_STB_IMAGE
#undef TINYGLTF_NO_INCLUDE_STB_IMAGE_WRITE
#undef TINYGLTF_USE_CPP14
#undef TINYGLTF_IMPLEMENTATION